### ISSUE TITLE
Is 1.16 possible?

### ISSUE THREAD

**Issue by Bettehem** [FukkitMC/fukkit#1]
Hello, your project looks very interesting!
My server is currently stuck on version 1.16.5 and I was wandering if it's somehow possible to get this working on it.

**Comment by builderpepc** [comment]
No offense to the devs, but I think [Cardboard](https://github.com/CardboardPowered/cardboard) is more stable and active right now. It works with 1.16.4, 1.16.5 and 1.17.1. A lot of plugins still have issues, though. You may want to look for Fabric alternatives to the plugins you want.

**Comment by TwilightFlower** [comment]
That developer is known for making completely fake mods. I would not trust anything with their name on it.

**Comment by Bettehem** [comment]
> That developer is known for making completely fake mods. I would not trust anything with their name on it.

The project is open source though and seems legitimate.

**Comment by AlsoSylv** [comment]
Open source doesn't equal safe, and cardboard is anything but legit.

**Comment by ramidzkh** [comment]
As previously said, the main cardboard developer isn't very reputable within the Fabric community.

Anyway, back to the main question, Fukkit does not yet work. This is because we are waiting on other people to finish their work so we can use it without reinventing the wheel.

Additionally, I don't think we will go back to supporting 1.16.5 again, as we have enough trouble trying to support latest. Please join the Discord server for updates!
